name: Create Release Branch
on:
  workflow_dispatch:
      
jobs:
  create-release-bracn:
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: 'master'

    - name: Find previous tag
      id: previous-tag
      uses: jimschubert/query-tag-action@v1
      with:
        include: 'v*'

    - name: Show previous tag
      id: display
      run: |
        echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'

    - name: Get next semver
      id: next-tag
      uses: WyriHaximus/github-action-next-semvers@v1
      with:
        version: ${{steps.previous-tag.outputs.tag}}

    - name: Show next tag
      id: display
      run: |
        echo 'Output from Find Tag: ${{steps.next-tag.outputs.v_minor}}'

    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: 'develop'

    - name: Create release branch
      run: git checkout -b release/${{ steps.next-tag.outputs.v_minor }}

    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com

    - name: Push new branch
      run: git push origin release/${{ steps.next-tag.outputs.v_minor }}

    - name: Create pull request into master
      uses: thomaseizinger/create-pull-request@1.2.1
      with:
        # github_token: ${{github.token}}
        head: release/${{ steps.next-tag.outputs.v_minor }}
        base: master
        title: Release ${{ steps.next-tag.outputs.v_minor }} into master
        # draft: true
