# This workflow will create a PR into develop for a release push (the PR to master for the release is created in cut-release.yml)
name: Create release PR into develop
on:
  push:
    branches:
      - release/*
jobs:   
  create-dev-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - # Create PR title based on the current ref, i.e:
        # "refs/heads/release/v1.5.0" -> "Release/v1.5.0"
        name: Generate PR title
        id: pr-title
        run: |
          param=$GITHUB_REF
          replaceMatch="refs/heads/"
          replaceValue=""
          result=${param/$replaceMatch/$replaceValue}
          echo "::set-output name=value::${result^}"

      - name: Create pull request into develop
        uses: thomaseizinger/create-pull-request@1.2.1
        with:
          github_token: ${{github.token}}
          head: ${{github.ref}}
          base: develop
          title: ${{steps.pr-title.outputs.value}} into develop
