# This workflow will create a PR into develop and master for a hotfix push
name: Create hotfix PR into develop and master
on:
  push:
    branches:
      - hotfix/*
jobs:   
  create-dev-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - # Create PR title based on the current ref, i.e:
        # "refs/heads/hotfix/KON-420" -> "Hotfix/KON-420"
        name: Generate PR title
        id: pr-title
        run: |
          param=$GITHUB_REF
          replaceMatch="refs/heads/"
          replaceValue=""
          result=${param/$replaceMatch/$replaceValue}
          echo "::set-output name=value::${result^}"

      - name: Create pull request into develop
        uses: thomaseizinger/create-pull-request@1.2.1
        with:
          github_token: ${{github.token}}
          head: ${{github.ref}}
          base: develop
          title: ${{steps.pr-title.outputs.value}} into develop
          draft: true

      - name: Create pull request into master
        uses: thomaseizinger/create-pull-request@1.2.1
        with:
          github_token: ${{github.token}}
          head: ${{github.ref}}
          base: master
          title: ${{steps.pr-title.outputs.value}} into master
